### PR TITLE
feat: add prop `init.svc.adbd` hiding

### PR DESCRIPTION
**Pull request by rushiranpise**

### CODE REVIEW

**Comment by rushiranpise** [comment]
For hiding from ruru, follow this guide https://github.com/rushiranpise/Hide-Debugging
Might Help with other apps too..

**Comment by rushiranpise** [comment]
https://github.com/xfqwdsj/IAmNotADeveloper/issues/4 https://github.com/xfqwdsj/IAmNotADeveloper/issues/9

**Review by xfqwdsj — CHANGES_REQUESTED** [review]
https://github.com/rovo89/XposedBridge/blob/a535c02ed9dfd53683cc0274d9f95bcb6ffb9f79/app/src/main/java/de/robv/android/xposed/XposedBridge.java#L167

According to the documentation, `XposedBridge.log()` is only used when an error is encountered. Please modify it. Thank you!

**Review by xfqwdsj — APPROVED** [review]

**Comment by xfqwdsj** [comment]
Nice!

**Pull request merged**
