### PR TITLE
Add SystemProperties hiding

### PR DESCRIPTION
**Pull request by rushiranpise**
Based on https://github.com/frknkrc44/DevOptsHide/commit/8ece0139ce70b18fc9cac6b3522c73d69a4ece4d

### CODE REVIEW

**Comment by rushiranpise** [comment]
seems it not working

**Comment by xfqwdsj** [comment]
Thank you for your contribution!  Since I'm a student, I don't have much time to maintain this project.  If you have any new progress, please feel free to submit a pull request!  I have a week off starting next week to work on this project.

In addition, this module has control switches for its functions.  Please add detailed switches for these new features.  I noticed that there are many bloated duplicates in my original code. If you are interested, please help me extract them. Thank you!

**Comment by rushiranpise** [comment]
> Thank you for your contribution! Since I'm a student, I don't have much time to maintain this project. If you have any new progress, please feel free to submit a pull request! I have a week off starting next week to work on this project.
> 
> In addition, this module has control switches for its functions. Please add detailed switches for these new features. I noticed that there are many bloated duplicates in my original code. If you are interested, please help me extract them. Thank you!

actually i was using ruru built from source , which shows incorrect status. i recheck with original release and it dont work

**Comment by xfqwdsj** [comment]
Anyway, it also makes sense to intercept the reading of props.  This is also part of my (no deadline) plan.

**Pull request closed without merging**
